### ISSUE TITLE
seems to be broken out of the box...

### ISSUE THREAD

**Issue by tomstace** [rgerum/pylustrator#45] opened 2022-08-25 02:41 UTC
I installed pylustrator on a macbook pro (intel) using pip.  No problems there.
Pasted the "test pylustrator" code from the documentation into jupyter lab, and got the following error.  Also tried VS Code, and same result.  Any idea what is happening? 
<img width="909" alt="image" src="https://user-images.githubusercontent.com/70620375/186561737-b59adf16-3236-4647-88cb-2c7a91889459.png">

**Comment by VictorSeven** [comment] 2022-10-05 10:54
I am also affected by this error (Ubuntu 16.04, with Jupyter Lab 3.3.2). Whenever I try just to import + start, I get an error that says `FileNotFoundError: '/tmp/ipykernel_9442/XXXXXXXX.py'` with numbers that change every time, so I guess it is some temporal file. A transparent windows appears, immediately closes, and the notebook prints this error (but the figure is drawn). Fresh installation from today, using just `pip`.  Is there any workaround?

**Comment by rgerum** [comment] 2022-10-05 11:44
Oh I guess its a problem with jupyter lab. I only implemented it to work with jupyter notebook. It basically tries to look for the file into which to paste the code for saving and apparently does not find the file as it is not started from a file. I haven't worked with jupyter lab yet. I will look into that.

**Comment by VictorSeven** [comment] 2022-10-05 17:45
I guess the error is related to that, but there the problem is _not_ limited to Jupyter Lab, since I tried also with Notebook (version 6.4.8) and I do receive the same error. The application works fine if I try to execute it from a python script, there is no problem.

**Comment by rgerum** [comment] 2022-10-05 19:58
Ah maybe it is then the bug #38 that was fixed in 225e208209465efe3324ea8b05a48daab21768b2

You can try to install the current github version with

pip install git+https://github.com/rgerum/pylustrator

and see if the bug still persists.

**Comment by VictorSeven** [comment] 2022-10-06 10:43
I cannot say on the previous error because now it gives an entire different problem. I'd say the current GitHub version is broken at master. 

First, I had to run `pip uninstall pylustrator` before running the command you suggested because the version has not changed and it is still 1.1.2. This means that pip will not make any changes, so I had to uninstall first. After that I run `pip install git+https://github.com/rgerum/pylustrator`, installed without problem. 

However, when I try to make `import pylustrator` now I have another error, let me paste the entire log here:

```
ModuleNotFoundError                       Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 import pylustrator

File ~/anaconda3/lib/python3.8/site-packages/pylustrator/__init__.py:22, in <module>
      1 #!/usr/bin/env python
      2 # -*- coding: utf-8 -*-
      3 # __init__.py
   (...)
     19 # You should have received a copy of the GNU General Public License
     20 # along with Pylustrator. If not, see <http://www.gnu.org/licenses/>
---> 22 from .QtGuiDrag import initialize as start
     23 from .helper_functions import fig_text, add_axes, add_image, despine, changeFigureSize, mark_inset, VoronoiPlot, selectRectangle, mark_inset_pos, draw_from_point_to_bbox, draw_from_point_to_point, loadFigureFromFile, add_letter, add_letters
     24 from .QtGui import initialize as StartColorChooser

File ~/anaconda3/lib/python3.8/site-packages/pylustrator/QtGuiDrag.py:38, in <module>
     35 from .drag_helper import DragManager
     36 from .exception_swallower import swallow_get_exceptions
---> 38 from .components.qitem_properties import QItemProperties
     39 from .components.tree_view import MyTreeView
     40 from .components.align import Align

ModuleNotFoundError: No module named 'pylustrator.components'

```
I  don't know where this is coming from. Thank you for your support!

**Comment by VictorSeven** [comment] 2022-10-06 19:52
I tried reinstalling and works like a charm. Thank you so so much!!. I would either update the pip packages soon or add a warning at the README so new users don't encounter this problem just after installation :)

**Comment by rgerum** [comment] 2022-10-24 20:05
I now published a new release. I hope this issue is now solved.

**Closed by rgerum** 2022-10-24 20:05 UTC
